### ISSUE TITLE
Selected Tab Color

### ISSUE THREAD

**Issue by bliet** [ahmed3elshaer/IntelliJ-True-Black-Theme#1]
In this theme there is no difference between the selected tab and other tabs.
I used this Theme, but additionaly changed the Color of "Settings -> Color Scheme -> General -> Editor -> Tabs -> Selected Tabs".

**Comment by btgn** [comment]
> In this theme there is no difference between the selected tab and other tabs. I used this Theme, but additionaly changed the Color of "Settings -> Color Scheme -> General -> Editor -> Tabs -> Selected Tabs".

Same issue here, I'm using the True Dark theme with Darcula color scheme but not able to see a difference between the selected tab and other tabs, could you get them added please

**Comment by ahmed3elshaer** [comment]
Hey, everyone. I have just released 1.4.5 that fixes this issue.

Fund fact: Selected tab indicator color was meant to be ignored as part of simplifying the crowded Intelij colors 😅
